### PR TITLE
Updating stories player component

### PR DESCRIPTION
**Pull request by filiptaticek**
Updating the stories player so that if language is changed, the story continues from the same part.

### CODE REVIEW

**Comment by JuroUhlar** [comment]
@filiptaticek Thanks for this! Unfortunately, we just merged a large update with Slovak fairytales which was in review for a while and created some conflicts. Do you mind resolving them? Thanks!

**Comment by filiptaticek** [comment]
> @filiptaticek Thanks for this! Unfortunately, we just merged a large update with Slovak fairytales which was in review for a while and created some conflicts. Do you mind resolving them? Thanks!

Actually, your merge is so large it is hard for me to recognize what have I changed, what have you changed and resolve the conflicts... do you mind if I close this pull request and create a new one, where I will start making changes from the current main branch?

**Comment by met** [comment]
@filiptaticek Ok, if it saves your time, make a new clean PR and close this one.

**Comment by JuroUhlar** [comment]
Closing this to avoid confusion

**Pull request closed without merging**
